routes/web.php
		Route::post('/update{id}', 'AboutServiceController@Update')->name('update');
		Route::get('/showadd', 'AboutServiceController@showAdd')->name('showadd');
		Route::post('/add', 'AboutServiceController@add')->name('add');
		Route::get('/destroy/{id}', 'AboutServiceController@destroy')->name('destroy');
		Route::get('/show/{id}', 'AboutServiceController@show')->name('show');
	});

	//services detail
	Route::group([
		'as'	=> 'services_detail.',
		'prefix' => 'services_detail',
	], function(){
		Route::get('/', 'Services_detailController@index')->name('dashboard');
		Route::get('/edit/{id}', 'Services_detailController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'Services_detailController@Update')->name('update');
		Route::get('/addservices_detail/{id}', 'Services_detailController@addServices_detail')->name('addServices_detail');
		Route::post('/add/{id}', 'Services_detailController@add')->name('add');
		Route::get('/destroy/{id}', 'Services_detailController@destroy')->name('destroy');
		Route::get('/show/{id}', 'Services_detailController@show')->name('show');
		Route::get('/list/{id}', 'Services_detailController@list')->name('list');
	});

	//User
	Route::group([
		'as'	=>'user.',
		'prefix'=>'user',
	], function(){
		Route::get('/', 'UserController@index')->name('dashboard');
		Route::get('/addUser', 'UserController@showFormAddUser')->name('showAddUser');
		Route::post('/postUser', 'UserController@addUser')->name('addUser');
		Route::get('/edit/{id}', 'UserController@showFormEditUser')->name('edit');
		Route::post('/update{id}', 'UserController@Update')->name('update');
		Route::get('/destroy/{id}', 'UserController@destroy')->name('destroy');
	});

	//about
	Route::group([
		'as'	=> 'about.',
		'prefix' => 'about',
	], function(){
		Route::get('/', 'AboutController@index')->name('dashboard');
		Route::get('/show/{id}', 'AboutController@show')->name('show');
		Route::get('/edit/{id}', 'AboutController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'AboutController@Update')->name('update');
		Route::get('/addabouts', 'AboutController@addAbout')->name('addAbout');
		Route::post('/add', 'AboutController@add')->name('add');
		Route::get('/destroy/{id}', 'AboutController@destroy')->name('destroy');
	});

	//slide
	Route::group([
		'as'	=> 'slide.',
		'prefix' => 'slide',
	], function(){
		Route::get('/', 'SlideController@index')->name('dashboard');
		Route::get('/edit/{id}', 'SlideController@showFormEditSlide')->name('edit');
		Route::post('/update{id}', 'SlideController@UpdateSlide')->name('update');
		Route::get('/addSlide', 'SlideController@addSlide')->name('addSlide');
		Route::post('/add', 'SlideController@add')->name('add');
		Route::get('/destroy/{id}', 'SlideController@destroy')->name('destroy');
	});



	Route::group([
		'as'	=> 'partner.',
		'prefix' => 'partner',
	], function(){
		Route::get('/', 'PartnerController@index')->name('dashboard');
		Route::get('/edit/{id}', 'PartnerController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'PartnerController@Update')->name('update');
		Route::get('/addpartner', 'PartnerController@addAbout')->name('addPartner');
		Route::post('/add', 'PartnerController@add')->name('add');
		Route::get('/destroy/{id}', 'PartnerController@destroy')->name('destroy');
		Route::get('/show/{id}', 'PartnerController@show')->name('show');
	});

	Route::group([
		'as'	=> 'ourteam.',
		'prefix' => 'ourteam',
	], function(){
		Route::get('/', 'OurteamController@index')->name('dashboard');
		Route::get('/edit/{id}', 'OurteamController@showFormEdit')->name('edit');
		Route::post('/update/{id}', 'OurteamController@Update')->name('update');
		Route::get('/addourteam', 'OurteamController@addAbout')->name('addOurteam');
		Route::post('/add', 'OurteamController@add')->name('add');
		Route::get('/destroy/{id}', 'OurteamController@destroy')->name('destroy');
		Route::get('/show/{id}', 'OurteamController@show')->name('show');
	});


	//Menu
	Route::group([
		'as'	=>'menu.',
		'prefix'=>'menu',
	], function(){
		Route::get('/', 'MenuController@index')->name('dashboard');
		Route::get('/addMenu', 'MenuController@showFormAddMenu')->name('showAddMenu');
		Route::post('/postMenu', 'MenuController@addMenu')->name('addMenu');
		Route::get('/edit/{id}', 'MenuController@showFormEditMenu')->name('edit');
		Route::post('/update{id}', 'MenuController@Update')->name('update');
		Route::get('/destroy/{id}', 'MenuController@destroy')->name('destroy');
	});

	//news
	Route::group([
		'as'	=> 'news.',
		'prefix' => 'news',
	], function(){
		Route::get('/', 'NewsController@index')->name('dashboard');
		Route::get('/edit/{id}', 'NewsController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'NewsController@Update')->name('update');
		Route::get('/addnews', 'NewsController@addNews')->name('addNews');
		Route::post('/add', 'NewsController@add')->name('add');
		Route::get('/destroy/{id}', 'NewsController@destroy')->name('destroy');
		Route::get('/show/{id}', 'NewsController@show')->name('show');
	});

	//Library
		Route::group([
		'as'	=> 'library.',
		'prefix' => 'library',
	], function(){
		Route::get('/', 'LibraryController@index')->name('dashboard');
		Route::get('/edit/{id}', 'LibraryController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'LibraryController@Update')->name('update');
		Route::get('/addlibrary', 'LibraryController@addLibrary')->name('addLibrary');
		Route::post('/add', 'LibraryController@add')->name('add');
		Route::get('/destroy/{id}', 'LibraryController@destroy')->name('destroy');
		Route::get('/show/{id}', 'LibraryController@show')->name('show');
		Route::get('/download/{id}', 'LibraryController@getDownload')->name('download');
	});

	//
	Route::group([
		'as'	=>'aboutpackage.',
		'prefix'=>'aboutpackage',
	], function(){
		Route::get('/', 'AboutPackageController@index')->name('dashboard');
		Route::get('/addaboutpackage', 'AboutPackageController@showFormAdd')->name('showAdd');
		Route::post('/postaboutpackage', 'AboutPackageController@add')->name('add');
		Route::get('/edit/{id}', 'AboutPackageController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'AboutPackageController@Update')->name('update');
		Route::get('/destroy/{id}', 'AboutPackageController@destroy')->name('destroy');
	});
	Route::group([
		'as'	=>'customercomment.',
		'prefix'=>'customercomment',
	], function(){
		Route::get('/', 'CustomerCommentController@index')->name('dashboard');
		Route::get('/addcustomercomment', 'CustomerCommentController@showFormAdd')->name('showAdd');
		Route::post('/postcustomercomment', 'CustomerCommentController@add')->name('add');
		Route::get('/edit/{id}', 'CustomerCommentController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'CustomerCommentController@Update')->name('update');
		Route::get('/destroy/{id}', 'CustomerCommentController@destroy')->name('destroy');
	});
});


//login
Route::group([
	'namespace' => 'Admin',
	'as'	=> 'login.',
	'prefix'=> 'login',
	// 'middleware' => ['FormLogin'],
], function(){
	Route::get('/', 'AdminLoginController@showlogin')->name('showlogin');
	Route::post('/login', 'AdminLoginController@login')->name('login');
	Route::any('logout', 'AdminLoginController@logout')->name('logout');
});
//end_login




Route::group([
	'middleware' => 'locale',
	'namespace' =>'Customer',
	'prefix'=>'',
	'as'	=> 'customer.',

], function(){

	Route::get('/', 'DashboardController@index')->name('dashboard')->middleware();

	// //About
	Route::group([
		'prefix'=>'',
		'as'	=> 'about.',

	], function(){
		Route::get('about', 'AboutController@showDataAbout')->name('showAbout');
	});

	//services
	Route::group([
		'prefix'=>'',
		'as'	=> 'services.',

	], function(){
		Route::get('/services', 'AboutController@showDataServices')->name('showServices');
	});

	//packages
	Route::group([
		'prefix'=>'',
		'as'	=> 'packages.',

	], function(){
		Route::get('/packages', 'AboutController@showDataPackages')->name('showPackages');
	});

	//partners
	Route::group([
		'prefix'=>'',
		'as'	=> 'partners.',

	], function(){
		Route::get('/partners', 'AboutController@showDataPartners')->name('showPartners');
		Route::get('/partners_detail', 'AboutController@showDataPartners_detail')->name('showPartners_detail');
	});
	//partners_detail

	Route::group([
		'prefix'=>'',
		'as'	=> 'about.',

	], function(){
		Route::get('/about_detail', 'AboutController@showDataAbout_detail')->name('showAbout_detail');
	});

	//Procedure
	Route::group([
		'prefix'=>'',
		'as'	=> 'procedure.',

	], function(){
		Route::get('/procedure', 'AboutController@showDataProcedure')->name('showProcedure');
	});

	//library
	Route::group([
		'prefix'=>'',
		'as'	=> 'library.',

	], function(){
		Route::get('/library', 'AboutController@showDataLibrary')->name('showLibrary');
		Route::get('/download/{id}', 'AboutController@getDownload')->name('download');
	});
	//library
	Route::group([
		'prefix'=>'',
		'as'	=> 'faqs.',

	], function(){
		Route::get('/faqs', 'AboutController@showDataFaqs')->name('showFaqs');
	});

	//news
	Route::group([
		'prefix'=>'',
		'as'	=> 'news.',

	], function(){
		Route::get('/news', 'AboutController@showDataNews')->name('showNews');
	});


	Route::group([
		'prefix'=>'',
		'as'	=> 'footer.',

	], function(){
		Route::get('/footer', 'AboutController@showDataFooter')->name('showFooter');
	});

    Route::get('/contact', 'AboutController@showContact')->name('showContact');

    Route::post('/contact', 'AboutController@sendContact');

    Route::get('/bemer', 'AboutController@showBemer');
    Route::get('/dr.lodi', 'AboutController@showDrLodi');
    Route::get('/dr.naim', 'AboutController@showDrNaim');
    Route::get('/blogs', 'BlogCustomerController@list')->name('listBlog');
    Route::get('/blogs/{id}', 'BlogCustomerController@detail')->name('detailBlog');

});
Route::group([
	'namespace'=>'Customer',
	'middleware' => 'locale',

],
	function() {
	Route::get('change-language/{language}', 'DashboardController@changeLanguage')

app/Http/Controllers/Customer/BlogCustomerController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Models\About;
use App\Models\BlogBanner;
use App\Models\Blogs;
use App\Models\Menu;
use App\Models\OurTeam;
use App\Models\Package;
use App\Models\Partner;
use App\Models\Tags;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class BlogCustomerController extends Controller
{
    public function list(Request $request) {
        if (session()->exists('website_language')) {
            $lang = $this->langs[session()->get('website_language')];
        }else{
            $lang = $this->langs['vi'];
        }
        $data = Menu::with(['abouts' => function ($query) use ($lang) {
            $query->where('lang_code', $lang);
        }])->where('lang_code',$lang)->get();

        $image = Menu::whereId(36)->get();


        $dv = DB::table('services')
            ->where('services.lang_code',$lang)
            ->join('services_detail', 'services_detail.services_id', '=', 'services.id')
            ->select('services.title', 'services_detail.title_con','services_detail.services_id','services_detail.content','services.icon','services_detail.links')
            ->get();
        $doingu = OurTeam::where('lang_code',$lang)->get();
        $title = About::where('lang_code',$lang)->get();
        $packages = Package::where('lang_code',$lang)->get();
        $partners = Partner::where('lang_code',$lang)->get();
        $where = [];
        if ($request->tag) {
            $where['blog_tag.tag_id'] = $request->tag;
        }
        if ($request->topic_id) {
            $where['blogs.topic_id'] = $request->topic_id;
        }
        $blogs = DB::table('blogs')->select('blogs.*', 'topics.name as topic_name')->join('blog_tag', 'blog_tag.blog_id', '=', 'blogs.id')
                    ->join('topics', 'topics.id', '=', 'blogs.topic_id')
                    ->where($where)->groupBy('blogs.id')->orderBy('blogs.id','desc')->get();
        $blogMost = Blogs::limit(3)->orderBy('view', 'desc')->get();
        $idBlogMost = array_map(function ($item) {
            return $item->id;
        }, $blogMost->all());

        $hotNews = Blogs::whereNotIn('id', $idBlogMost)->limit(3)->orderBy('id')->get();
        $tags = Tags::limit(20)->get();

        return view('customer.blogs.list', compact('data','title','blogs','dv','image','doingu','packages','partners', 'tags', 'blogMost', 'hotNews'));
    }

    public function detail($id) {
        if (session()->exists('website_language')) {
            $lang = $this->langs[session()->get('website_language')];
        }else{
            $lang = $this->langs['vi'];
        }
        $data = Menu::with(['abouts' => function ($query) use ($lang) {
            $query->where('lang_code', $lang);
        }])->where('lang_code',$lang)->get();/*dd($data);*/

        $image = Menu::whereId(36)->get();


        $dv = DB::table('services')
            ->where('services.lang_code',$lang)
            ->join('services_detail', 'services_detail.services_id', '=', 'services.id')
            ->select('services.title', 'services_detail.title_con','services_detail.services_id','services_detail.content','services.icon','services_detail.links')
            ->get();
        $doingu = OurTeam::where('lang_code',$lang)->get();
        $title = About::where('lang_code',$lang)->get();
        $packages = Package::where('lang_code',$lang)->get();
        $partners = Partner::where('lang_code',$lang)->get();
        $blog = Blogs::with('topics', 'blogTag')->find($id);
        Blogs::where('id', '=', $id)->update(['view' => $blog->view + 1]);
        $blogTopic = Blogs::where([['topic_id', '=', $blog->topic_id], ['id', '<>', $blog->id]])->limit(6)->get();
        $blogMost = Blogs::limit(3)->orderBy('view', 'desc')->get();
        $idBlogMost = array_map(function ($item) {
            return $item->id;
        }, $blogMost->all());

        $hotNews = Blogs::whereNotIn('id', $idBlogMost)->limit(3)->orderBy('id')->get();
        $blogBanner = BlogBanner::where('status', '=', 1)->limit(1)->first();
        return view('customer.blogs.detail', compact('data','title','dv','image','doingu','packages','partners', 'blog', 'blogTopic', 'blogMost', 'hotNews', 'blogBanner'));
    }
}

app/Http/Controllers/Customer/DashboardController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Package;
use App\Models\Partner;
use App\Models\Service;
use App\Models\Services_detail;
use Illuminate\Support\Facades\DB;
use App\Models\Slide;
use App\Models\Menu;
use App\Models\OurTeam;
use App\Models\About;
use App\Models\AboutPackage;
use App\Models\AboutService;
use App\Models\CustomerComments;
class DashboardController extends Controller
{
    public function index(){
         
        if (session()->exists('website_language')) {
            $lang = $this->langs[session()->get('website_language')];
        }else{
            $lang = $this->langs['vi'];
        }
    	$package = AboutPackage::where('lang_code',$lang)->paginate(3);
    	$partner = Partner::where('lang_code',$lang)->get();

    	$slide = Slide::where('lang_code',$lang)->get();
        $data = Menu::with(['abouts' => function ($query) use ($lang) {
            $query->where('lang_code', $lang);
        }])->where('lang_code',$lang)->get();

        $image = Menu::whereId(23)->get();

        $dv = DB::table('service_homes')
            ->where('service_homes.lang_code',$lang)
            ->join('services', 'service_homes.services_id', '=', 'services.id')
            ->select('services.title', 'services.link', 'service_homes.content', 'service_homes.image')
            ->paginate(4);
        $services_details = Services_detail::where('lang_code',$lang)->get();
           

        $doingu = OurTeam::where('lang_code',$lang)->get();
        $title = About::where('lang_code',$lang)->get();
        
    	$service = Service::where('lang_code',$lang)->paginate(4);
        $comment = CustomerComments::where('lang_code',$lang)->get();
    	return view('customer.dashboard.dashboard', compact('package', 'partner', 'service', 'slide', 'data','title','dv','image','doingu', 'comment', 'services_details'));

    }
    public function changeLanguage($language)
    {

        \Session::put('website_language', $language);

        return redirect()->back();
    }
}

app/Http/Controllers/Customer/HomeController.php
<?php

namespace App\Http\Controllers\customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    //
	public function changeLanguage($language)
	{
		\Session::put('website_language', $language);

		return redirect()->back();
	}
}

resources/views/customer/bemer.blade.php
@extends('customer.layout')

@section('header')
<div class="container">
	<div class="row">
		<div class="header-top">
			<div class="col-md-3 col-sm-3 col-xs-6 col-md">
				<div class="logo">
					<a href="/">
						<img class=" img-logo-color" src="content/img/color_logo_3 (1).png" style="display: none">
						<img class="img-logo" src="content/img/color_logo_2.png">
					</a>
				</div>
			</div>
			<div class="col-md-9 col-sm-9" style="padding-left: 0;padding-right: 0">
							<!-- <div class="col-lg-6 col-md-6 col-sm-3 hide-fix hidden-xs ms-hide" style="padding: 15px 0 0">
								<div class="logo-text">
									<span><i class="far fa-clock"></i>Chúng tôi mở cửa 24/7, bao gồm cả ngày lễ và cuối tuần</span>
								</div>
							</div> -->
							<div class="col-sm-3 hidden-xs hidden-lg hidden-md" style="padding: 0">
								<div class="hotline">
									<span class="montserrat">
										<img src="content/img/telephone.png" class="tel">
										<img src="content/img/telephone (1).png" class="tel1">
										<a href="tel:19003053">1900 3053</a>
									</span>
								</div>
							</div>
							<div class="col-lg-12 col-md-9 col-sm-9 hide-fix hidden-xs ms-right"  style="padding: 15px 0 0">
								<div class="menu-top">
									<ul>
										<li><a href="/news">{{__('menus.news')}}</a></li>
												<li><a href="/faqs#cau-hoi-thuong-gap">{{__('menus.faq')}}</a></li>
												<li><a href="/services#footer">{{__('menus.contact')}}</a></li>
										<li class="social">
											<a href="https://www.facebook.com/infinityhealthcarevietnam/" style="padding: 5px 10px;"><i class="fa fa-facebook-f"></i></a>
											<a href="https://www.youtube.com/channel/UCgacemtU2bpQLcWTsTZhYWg/featured?view_as=subscriber" style="padding: 5px 8px;"><i class="fa fa-youtube"></i></a>
											<a style="padding: 5px ;" href="{!! route('user.change-language', ['vi']) !!}">VN</a>
											<a style="padding: 5px 6px;" href="{!! route('user.change-language', ['en']) !!}">EN</a>
											<!-- <a style="padding: 5px 6px;" href="{!! route('user.change-language', ['ja']) !!}">JA</a> -->
										</li>
									</ul>
								</div>
							</div>
							<div class="col-lg-10 col-md-9 col-sm-12" style="padding-left: 0;padding-right: 0">
								<div id="sub-menu">
									<div id="cssmenu">
										<ul >
											<li><a href="/">{{__('menus.home')}}</a></li>

											@foreach($data as $menus)
											<li class="has-sub ">
												<a href="{{ $menus->links}}" class="mobile-a" id="{{$menus->id}}">{{__('menus.'.$menus->name)}}</a>

												<ul >
													@if($menus->links == '/about')
														@foreach($menus->abouts as $titles)
														<li><a href="{{route('customer.about.showAbout')}}#{{$titles->links}}">{{$titles->title}}</a></li>
														@endforeach
													@endif

													@if($menus->links == '/partners')
														@foreach($menus->partners as $titles)
														<li><a href="{{route('customer.partners.showPartners_detail')}}#{{$titles->id}}#{{$titles->id}}">{{$titles->title}}</a></li>
														@endforeach
													@endif
												</ul>

											</li>
											@endforeach


											<li class="hidden-lg hidden-md hidden-sm">
												<div class="mobile-menu">
													<div class="menu-top">
														<ul class="eg">
															<li><a >Tin tức</a></li>
															<li><a href="faqs.html">Hỏi đáp</a></li>
															<li><a href="#footer">Liên hệ</a></li>
															<li class="has-sub">
																<a>English</a>
																<ul>
																	<li><a style="padding: 5px ;" href="index.html">VN</a></li>
																	<li><a style="padding: 5px 6px;" href="index.en.html">EN</a></li>
																</ul>
															</li>
															<li class="social social-mobile">
																<a ><i class="fa fa-facebook-f"></i></a>
																<a ><i class="fa fa-youtube"></i></a>
															</li>
														</ul>
													</div>
												</div>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="col-lg-2 col-md-3 hidden-xs hidden-sm" style="padding: 0">
								<div class="hotline">
									<span class="montserrat">
										<img src="content/img/telephone.png" class="tel">
{{--										<img src="content/img/telephone (1).png" class="tel1">--}}
										<a href="tel:19003053"> 1900 3053</a>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			@endsection

			@section('content')
            @endsection

resources/views/customer/footer.blade.php
<footer id="footer">
    <div class="footer">
        <div class="container">
            <div class="row flex-ft">
                <div class="col-md-6 col-xs-12 pd-0" style="margin-right: 30px">
                    <div class="img-logo-footer">
                        <a href="/">
                            <img src="content/img/color_logo_2.png">
                        </a>
                    </div>
                </div>
            </div>
            <div class="row flex-ft">
                <div class="col-md-6 col-xs-12 pd-0" style="margin-right: 30px">

                    <h3 class="title-footer text-capitalize title-main-footer">{{ __('home.company_name') }}</h3>
                    <div class="add clickin">
                        <p class="mst">{{ __('home.tax_code') }}: 0315190682</p>
                    </div>
                    <div class="add clickin">
                        <p>{{ __('home.head_office') }}:</p>
                        <p>{{ __('home.head_office_address') }}</p>
                    </div>
                    <div class="add clickin">
                        <p>{{ __('home.hanoi_office') }}:</p>
                        <p>{{ __('home.hanoi_office_address') }}</p>
                    </div>
                </div>
                <div class="flex-menu col-md- col-xs-12">
                    <h3 class="title-footer text-uppercase mbx-15">Menu</h3>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="list-footer clickin">
                                <ul>
                                    <li><a href="/">{{ __('menus.home') }}</a></li>
                                    <li><a href="/about" class="mobile-a" id="23">{{__('menus.Giới thiệu')}}</a></li>
                                    <li><a href="/services" class="mobile-a" id="29">{{__('menus.Dịch vụ')}}</a></li>
                                    <li><a href="/packages" class="mobile-a" id="30">{{__('menus.Gói trị liệu')}}</a>
                                    </li>
                                    <li><a href="/partners" class="mobile-a" id="34">{{__('menus.Đối tác')}}</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="list-footer clickin">
                                <ul>
                                    <li><a href="/news" class="mobile-a" id="23">{{__('menus.Tin tức')}}</a></li>
                                    <li><a href="/procedure" class="mobile-a" id="35">{{__('menus.Thủ tục')}}</a></li>
                                    <li><a href="/library" class="mobile-a" id="36">{{__('menus.Thư viện')}}</a></li>
                                    <li><a href="/faqs#cau-hoi-thuong-gap"
                                           class="mobile-a">{{__('menus.Hỏi đáp')}}</a>
                                    <li><a href="/contact" class="mobile-a">{{__('menus.Liên hệ')}}</a>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12">
                    <h3 class="title-footer text-uppercase mbx-15" id="lien-he">{{ __('home.information') }}</h3>
                    <div class="form-footer clickin" style="color: #acbaca">
                        <p><i class="fa fa-clock-o" style="margin-right: 10px" aria-hidden="true"></i> 8:00 -
                            17:00 {{ __('home.monday') }} - {{ __('home.saturday') }}</p>
                        <p><i class="fa fa-phone" style="margin-right: 10px" aria-hidden="true"></i> 1900 3053</p>
                        <p><i class="fa fa-envelope-o" style="margin-right: 10px" aria-hidden="true"></i>
                            info@infinityhealthcare.vn</p>
                    </div>
                    <div>
                        <ul class="ul-footer">
                            <li class="follow text-uppercase" style="color: #a9bcd2">{{ __('home.social_media') }}</li>
                            <li class="social" style="min-width:100px;">
                                <a class="socail-icon" href="https://www.facebook.com/infinityhealthcarevietnam/" target="_blank"><i class="fa fa-facebook-f"></i></a>
                                <a class="socail-icon" href="https://www.youtube.com/channel/UCgacemtU2bpQLcWTsTZhYWg" target="_blank"><i class="fa fa-youtube"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="text-left pull-left  color-22">
                    <p>© {{__('home.copyright')}}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div id="back-to-top" class="back-to-top" data-toggle="tooltip" data-placement="left" title="Trở lên đầu trang">
        <i class="fa fa-angle-up"></i>
    </div>
    <div class="hidden-lg hidden-md hidden-sm phone-gif">
        <a href="tel:19003053"><img src="content/img/Homepage/icon-phone.gif"></a>
    </div>
</footer>