routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'DashboardController@index');


use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin'], function(){
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::get('/getadd', 'AdminController@getadd')->name('getadd');
	Route::post('/add', 'AdminController@add')->name('add');


});

Route::group([
	'namespace' =>'Admin',
	'prefix'=>'admin',
	'as'	=> 'admin.',
	'middleware'=>['web','checkAdmin']
], function(){
    $website_language = session()->get('website_language');
    if ($website_language == null){
        session()->put('website_language', 'vi');
    }
	Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('blogs', 'BlogController');
    Route::resource('topics', 'TopicController');
    Route::resource('tags', 'TagController');
    Route::resource('blog_banner', 'BlogBannerController');
    Route::post('/hot_news', 'BlogController@hotNews')->name('hotNews');
    Route::post('/active', 'BlogBannerController@active')->name('activeBanner');
	//package
	Route::group([
		'prefix'=>'package',
		'as'	=> 'package.'

	], function(){
		Route::get('/', 'PackagesController@showDataPackage')->name('showPackage');
		Route::get('/viewPackage/{id}', 'PackagesController@showDetailPackage')->name('detailPackage');
		Route::get('/addPackage', 'PackagesController@showFormAddPackage')->name('showAddPackage');
		Route::post('/postPackage', 'PackagesController@addPackage')->name('addPackage');
		Route::get('/editPackage/{id}', 'PackagesController@showFormEditPackage')->name('ShowEditPackage');
		Route::post('/update/{id}', 'PackagesController@update')->name('update');
		Route::get('/destroy/{id}', 'PackagesController@destroy')->name('destroy');
	});

	//Service
	Route::group([
		'as'	=> 'service.',
		'prefix' => 'service',
	], function(){
		Route::get('/', 'ServicesController@index')->name('dashboard');
		Route::get('/edit/{id}', 'ServicesController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'ServicesController@Update')->name('update');
		Route::get('/addservice', 'ServicesController@addService')->name('addService');
		Route::post('/add', 'ServicesController@add')->name('add');
		Route::get('/destroy/{id}', 'ServicesController@destroy')->name('destroy');
		Route::get('/show/{id}', 'ServicesController@show')->name('show');
	});


	//services detail
	Route::group([
		'as'	=> 'about_service.',
		'prefix' => 'about_service',
	], function(){
		Route::get('/', 'AboutServiceController@index')->name('dashboard');
		Route::get('/edit/{id}', 'AboutServiceController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'AboutServiceController@Update')->name('update');
		Route::get('/showadd', 'AboutServiceController@showAdd')->name('showadd');
		Route::post('/add', 'AboutServiceController@add')->name('add');
		Route::get('/destroy/{id}', 'AboutServiceController@destroy')->name('destroy');
		Route::get('/show/{id}', 'AboutServiceController@show')->name('show');
	});

	//services detail
	Route::group([
		'as'	=> 'services_detail.',
		'prefix' => 'services_detail',
	], function(){
		Route::get('/', 'Services_detailController@index')->name('dashboard');
		Route::get('/edit/{id}', 'Services_detailController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'Services_detailController@Update')->name('update');
		Route::get('/addservices_detail/{id}', 'Services_detailController@addServices_detail')->name('addServices_detail');
		Route::post('/add/{id}', 'Services_detailController@add')->name('add');
		Route::get('/destroy/{id}', 'Services_detailController@destroy')->name('destroy');
		Route::get('/show/{id}', 'Services_detailController@show')->name('show');
		Route::get('/list/{id}', 'Services_detailController@list')->name('list');
	});

	//User
	Route::group([
		'as'	=>'user.',
		'prefix'=>'user',
	], function(){
		Route::get('/', 'UserController@index')->name('dashboard');
		Route::get('/addUser', 'UserController@showFormAddUser')->name('showAddUser');
		Route::post('/postUser', 'UserController@addUser')->name('addUser');
		Route::get('/edit/{id}', 'UserController@showFormEditUser')->name('edit');
		Route::post('/update{id}', 'UserController@Update')->name('update');
		Route::get('/destroy/{id}', 'UserController@destroy')->name('destroy');
	});

	//about
	Route::group([
		'as'	=> 'about.',
		'prefix' => 'about',
	], function(){
		Route::get('/', 'AboutController@index')->name('dashboard');
		Route::get('/show/{id}', 'AboutController@show')->name('show');
		Route::get('/edit/{id}', 'AboutController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'AboutController@Update')->name('update');
		Route::get('/addabouts', 'AboutController@addAbout')->name('addAbout');
		Route::post('/add', 'AboutController@add')->name('add');
		Route::get('/destroy/{id}', 'AboutController@destroy')->name('destroy');
	});

	//slide
	Route::group([
		'as'	=> 'slide.',
		'prefix' => 'slide',
	], function(){
		Route::get('/', 'SlideController@index')->name('dashboard');
		Route::get('/edit/{id}', 'SlideController@showFormEditSlide')->name('edit');
		Route::post('/update{id}', 'SlideController@UpdateSlide')->name('update');
		Route::get('/addSlide', 'SlideController@addSlide')->name('addSlide');
		Route::post('/add', 'SlideController@add')->name('add');
		Route::get('/destroy/{id}', 'SlideController@destroy')->name('destroy');
	});



	Route::group([
		'as'	=> 'partner.',
		'prefix' => 'partner',
	], function(){
		Route::get('/', 'PartnerController@index')->name('dashboard');
		Route::get('/edit/{id}', 'PartnerController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'PartnerController@Update')->name('update');
		Route::get('/addpartner', 'PartnerController@addAbout')->name('addPartner');
		Route::post('/add', 'PartnerController@add')->name('add');
		Route::get('/destroy/{id}', 'PartnerController@destroy')->name('destroy');
		Route::get('/show/{id}', 'PartnerController@show')->name('show');
	});

	Route::group([
		'as'	=> 'ourteam.',
		'prefix' => 'ourteam',
	], function(){
		Route::get('/', 'OurteamController@index')->name('dashboard');
		Route::get('/edit/{id}', 'OurteamController@showFormEdit')->name('edit');
		Route::post('/update/{id}', 'OurteamController@Update')->name('update');
		Route::get('/addourteam', 'OurteamController@addAbout')->name('addOurteam');
		Route::post('/add', 'OurteamController@add')->name('add');
		Route::get('/destroy/{id}', 'OurteamController@destroy')->name('destroy');
		Route::get('/show/{id}', 'OurteamController@show')->name('show');
	});


	//Menu
	Route::group([
		'as'	=>'menu.',
		'prefix'=>'menu',
	], function(){
		Route::get('/', 'MenuController@index')->name('dashboard');
		Route::get('/addMenu', 'MenuController@showFormAddMenu')->name('showAddMenu');
		Route::post('/postMenu', 'MenuController@addMenu')->name('addMenu');
		Route::get('/edit/{id}', 'MenuController@showFormEditMenu')->name('edit');
		Route::post('/update{id}', 'MenuController@Update')->name('update');
		Route::get('/destroy/{id}', 'MenuController@destroy')->name('destroy');
	});

	//news
	Route::group([
		'as'	=> 'news.',
		'prefix' => 'news',
	], function(){
		Route::get('/', 'NewsController@index')->name('dashboard');
		Route::get('/edit/{id}', 'NewsController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'NewsController@Update')->name('update');
		Route::get('/addnews', 'NewsController@addNews')->name('addNews');
		Route::post('/add', 'NewsController@add')->name('add');
		Route::get('/destroy/{id}', 'NewsController@destroy')->name('destroy');
		Route::get('/show/{id}', 'NewsController@show')->name('show');
	});

	//Library
		Route::group([
		'as'	=> 'library.',
		'prefix' => 'library',
	], function(){
		Route::get('/', 'LibraryController@index')->name('dashboard');
		Route::get('/edit/{id}', 'LibraryController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'LibraryController@Update')->name('update');
		Route::get('/addlibrary', 'LibraryController@addLibrary')->name('addLibrary');
		Route::post('/add', 'LibraryController@add')->name('add');
		Route::get('/destroy/{id}', 'LibraryController@destroy')->name('destroy');
		Route::get('/show/{id}', 'LibraryController@show')->name('show');
		Route::get('/download/{id}', 'LibraryController@getDownload')->name('download');
	});

	//
	Route::group([
		'as'	=>'aboutpackage.',
		'prefix'=>'aboutpackage',
	], function(){
		Route::get('/', 'AboutPackageController@index')->name('dashboard');
		Route::get('/addaboutpackage', 'AboutPackageController@showFormAdd')->name('showAdd');
		Route::post('/postaboutpackage', 'AboutPackageController@add')->name('add');
		Route::get('/edit/{id}', 'AboutPackageController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'AboutPackageController@Update')->name('update');
		Route::get('/destroy/{id}', 'AboutPackageController@destroy')->name('destroy');
	});
	Route::group([
		'as'	=>'customercomment.',
		'prefix'=>'customercomment',
	], function(){
		Route::get('/', 'CustomerCommentController@index')->name('dashboard');
		Route::get('/addcustomercomment', 'CustomerCommentController@showFormAdd')->name('showAdd');
		Route::post('/postcustomercomment', 'CustomerCommentController@add')->name('add');
		Route::get('/edit/{id}', 'CustomerCommentController@showFormEdit')->name('edit');
		Route::post('/update{id}', 'CustomerCommentController@Update')->name('update');
		Route::get('/destroy/{id}', 'CustomerCommentController@destroy')->name('destroy');
	});
});


//login
Route::group([
	'namespace' => 'Admin',
	'as'	=> 'login.',
	'prefix'=> 'login',

app/Models/Tags.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tags extends Model
{
    //
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\BlogTag;
use App\Models\Tags;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tags::paginate(15);
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255'
        ],
            [
                'required' => 'The :attribute field is required.',
            ]);
        $updateData = $request->all();
        unset($updateData['_method']);
        unset($updateData['_token']);
        if (Tags::insert($updateData)) {
            return redirect()->route('admin.tags.index')->with('message', 'Thêm mới thành công');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tags::find($id);
        return view('admin.tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255'
        ],
            [
                'required' => 'The :attribute field is required.',
            ]);
        $updateData = $request->all();
        unset($updateData['_method']);
        unset($updateData['_token']);
        if (Tags::where('id', '=', $id)->update($updateData)) {
            return redirect()->route('admin.tags.index')->with('message', 'Chỉnh sửa thành công');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Tags::find($id)->delete()) {
            BlogTag::where('tag_id', '=', $id)->delete();
            return redirect()->route('admin.tags.index')->with('message', 'Xoá thành công');
        } else {
            return redirect()->route('admin.tags.index')->with('error', 'Đã có lỗi xảy ra');
        }
    }
}

resources/views/admin/tags/create.blade.php
@extends('admin.layout')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('admin.dashboard')}}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{route('admin.tags.index')}}">Tags</a>
        </li>
        <li class="breadcrumb-item active">Tạo mới</li>
    </ol>
    <pre></pre>
    <div class="row">
        @if (Session::has('fail'))
            <div class="alert alert-danger">{{ Session::get('fail') }}</div>
        @endif
    </div>
    <form action="{{route('admin.tags.store')}}" method="POST" role="form"  enctype="multipart/form-data">
        <legend>Thêm tags</legend>
        <br>
        @csrf
        {{--        <div class="form-group">--}}
        {{--            <label for="namePd">Ngôn ngữ:</label>--}}
        {{--            <select name="lang_code">--}}
        {{--                @foreach ($lang_code as $key => $value)--}}
        {{--                    <option value="{{ $key  }}" @if($key == $blog->lang_code) selected @endif >{{$value}}</option>--}}
        {{--                @endforeach--}}
        {{--            </select>--}}
        {{--        </div>--}}
        <div class="form-group">
            <label for="">Tags</label>
            <input type="text" class="form-control" id="" placeholder="tags"  name="name" value="{{ old('name') }}">
            @if($errors->has('name'))
                <div class="alert alert-danger">{{ $errors->first('name') }}</div>
            @endif
        </div>


        <button type="submit" class="btn btn-primary">Thêm</button>
        <a href="#" data-toggle="modal" data-target="#back"class="btn btn-danger">Hủy bỏ</a>
        <div class="modal fade" id="back" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">Bạn chắc chắn muốn thoát không lưu chứ? </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-danger" href="{{route('admin.topics.index')}}">OK</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <br><br>

@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layout')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('admin.dashboard')}}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{route('admin.topics.index')}}">Tags</a>
        </li>
        <li class="breadcrumb-item active">Sửa</li>
    </ol>
    <a href="{{route('admin.tags.create')}}" class="btn btn-info"><i class="fa fa-plus"></i> Thêm Tags</a>
    <pre></pre>
    <div class="row">
        @if (Session::has('fail'))
            <div class="alert alert-danger">{{ Session::get('fail') }}</div>
        @endif
    </div>
    <form action="{{route('admin.tags.update', $tag->id)}}" method="POST" role="form"  enctype="multipart/form-data">
        @method('PUT')
        <legend>Sửa tag</legend>
        <br>
        @csrf
        {{--        <div class="form-group">--}}
        {{--            <label for="namePd">Ngôn ngữ:</label>--}}
        {{--            <select name="lang_code">--}}
        {{--                @foreach ($lang_code as $key => $value)--}}
        {{--                    <option value="{{ $key  }}" @if($key == $blog->lang_code) selected @endif >{{$value}}</option>--}}
        {{--                @endforeach--}}
        {{--            </select>--}}
        {{--        </div>--}}
        <div class="form-group">
            <label for="">Tags</label>
            <input type="text" class="form-control" id="" placeholder="Tags"  name="name" value="{{ old('name') ?? $tag->name }}">
            @if($errors->has('name'))
                <div class="alert alert-danger">{{ $errors->first('name') }}</div>
            @endif
        </div>


        <button type="submit" class="btn btn-primary">Sửa</button>
        <a href="#" data-toggle="modal" data-target="#back{{$tag->id}}"class="btn btn-danger">Hủy bỏ</a>
        <div class="modal fade" id="back{{$tag->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">Bạn chắc chắn muốn thoát không lưu chứ? </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-danger" href="{{route('admin.topics.index')}}">OK</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <br><br>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layout')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{route('admin.dashboard')}}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Tags</li>
    </ol>
    <a href="{{route('admin.tags.create')}}" class="btn btn-info"><i class="fa fa-plus"></i> Tạo Tags</a>
    <pre></pre>
    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @else
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif

    <table class="table table-hover">
        <thead>
        <tr>
            <th>#</th>
            <th>Tags</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($tags as $val)
            <tr>
                <td>{{$loop->index + 1}}</td>
                <td>{{$val->name}}</td>
                <td>
                    <a href="{{route('admin.tags.edit', $val->id)}}" class="btn btn-primary">Sửa</a>
                    <a href="#" data-toggle="modal" data-target="#delete{{$val->id}}"class="btn btn-danger">Xoá</a>
                </td>

            </tr>
            <div class="modal fade" id="delete{{$val->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-body">Bạn chắc chắn muốn xoá chứ? </div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                            <form action="{{route('admin.tags.destroy', $val->id)}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        @endforeach
        </tbody>
    </table>
    <div class="m-auto">
        {{ $tags->links() }}
    </div>
    <br>
    <br>
@endsection